import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
      <head>
      <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css"
          integrity="sha512-dkY6W7K+mzUSzi0OlLbvzjP7fUpuHgALZstR9pH+vqZ0PNExuYzFzR4O8f2h1xOm3ceG6Y2NdeHE7GyBqK+9BA=="
          crossOrigin="anonymous"
          referrerPolicy="no-referrer"
        />
      </head>
    </html>
  );
}
